//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCBankingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeingAccount
    {
        public int cheque_acct_id { get; set; }
        public int account_id { get; set; }
        public long account_number { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
    }
}
